language: go

go:
- "1.12"

env:
- GO111MODULE=on

services:
- mongodb

install: make dep-install

before_script:
- curl -LO https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait
- chmod +x wait
- WAIT_HOSTS="localhost:27017" ./wait

script: make test
